version: '3'
services:
    web:
      image: nginx:alpine
      ports:
        - '8080:80'
      volumes:
        - ./frontend:/usr/share/nginx/html
      depends_on:
        - db
    backend:
      build: ./backend
      ports:
        - '3000:3000'
    db:
      image: mysql:8.0
      command: ['--default-authentication-plugin=mysql_native_password']
      ports:
      - "3306:3306"
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      volumes:
        - node_backup:/var/lib/mysql