version: '3'
services:
    web:
      image: nginx:alpine
      ports:
        - '8080:80'
      volumes:
        - ./frontend:/usr/share/nginx/html
      depends_on:
        - db
    backend:
      build: ./backend
      ports:
        - '3000:3000'